In [1]:
import numpy as np
import pandas as pd
import folium, requests
from folium.plugins import HeatMap
import requests,json,os
from urllib.parse import quote

In [2]:
df = pd.read_csv('data/main/lines/2호선.csv')
df.head()

,사용월,호선명,지하철역,출근시간 승차인원,출근시간 하차인원,09-16시 승차인원,09-16시 하차인원,퇴근시간 승차인원,퇴근시간 하차인원,새벽 승차인원,새벽 하차인원,야간 승차인원,야간 하차인원,총 승차인원,총 하차인원
0,201501,2호선,강남,189760,701902,1042394,1603485,997168,769132,21847,14679,1059691,326193,2313692,2646259
1,201501,2호선,강변,293580,145018,686307,565678,293385,424408,10783,4758,211377,331701,1202047,1047155
2,201501,2호선,건대입구,225559,121100,431191,486054,271968,485591,23981,2167,370016,351397,1050747,960718
3,201501,2호선,교대,90862,269377,402326,622114,361967,243584,3676,6374,281092,136558,777956,1034423
4,201501,2호선,구로디지털단지,422624,409123,623114,596323,511836,458490,40909,6198,306909,443872,1393556,1455516