In [8]:
import numpy as np
import pandas as pd
import folium, requests
from folium.plugins import HeatMap
import requests,json,os
from urllib.parse import quote

In [9]:
df = pd.read_csv('latlng_merge_test.csv')
df.head()

,사용월,호선명,지하철역,출근시간 하차인원,09-16시 승차인원,09-16시 하차인원,퇴근시간 승차인원,퇴근시간 하차인원,새벽 승차인원,새벽 하차인원,야간 승차인원,야간 하차인원,총 승차인원,총 하차인원,lat,lng
0,201501,1호선,가능,23287,96744,66805,31775,60948,8225,1240,17566,55647,190620,146979,37.748369,127.044221
1,201501,1호선,가산디지털단지,230457,107638,189559,209852,86319,8884,1544,114317,58461,274951,480021,37.481596,126.882559
2,201501,1호선,간석,15467,78718,55206,28721,55488,5554,1282,17595,56137,164392,128092,37.464688,126.693451
3,201501,1호선,개봉,52104,280814,191890,90855,217153,15614,3593,50829,184806,565027,432393,37.494522,126.859103
4,201501,1호선,관악,22169,100507,83845,40644,65829,6103,1307,19637,61074,210027,168395,37.418802,126.909121

In [10]:
df1 = df[['사용월','지하철역','총 승차인원','총 하차인원','lat','lng']].copy()
df1.head()

      사용월     지하철역  총 승차인원  총 하차인원        lat         lng
0  201501       가능  190620  146979  37.748369  127.044221
1  201501  가산디지털단지  274951  480021  37.481596  126.882559
2  201501       간석  164392  128092  37.464688  126.693451
3  201501       개봉  565027  432393  37.494522  126.859103
4  201501       관악  210027  168395  37.418802  126.909121

In [11]:
df1 = df1[(df1['사용월'] >= 202301) & (df['사용월'] < 202305)].copy()
df1.head()

         사용월     지하철역  총 승차인원  총 하차인원        lat         lng
9882  202301       가능  138903  107555  37.748369  127.044221
9883  202301  가산디지털단지  202304  425833  37.481596  126.882559
9884  202301       간석  123059   91014  37.464688  126.693451
9885  202301       개봉  478140  334667  37.494522  126.859103
9886  202301       관악  161565  116297  37.418802  126.909121

In [13]:
res = df1.groupby('지하철역')[['총 승차인원','총 하차인원','lat','lng']].agg('mean').reset_index()
res.head()

      지하철역     총 승차인원     총 하차인원        lat         lng
0       가능  153126.25  119310.50  37.748369  127.044221
1  가산디지털단지  219895.25  449729.75  37.481596  126.882559
2       간석  135008.00   98793.00  37.464688  126.693451
3       개봉  522096.25  362515.25  37.494522  126.859103
4       관악  181167.25  129167.25  37.418802  126.909121

In [14]:
res2 = res[['lat','lng','총 승차인원']]

In [17]:

# 지도 생성
m = folium.Map(location=[37.394946, 127.111104], zoom_start=12)
# 데이터
HeatMap(
    data=res2, 
    radius=8,
).add_to(m)
m
#