In [1]:
import pandas as pd
import numpy as np

In [2]:
# 주말 파일 불러옴
df = pd.read_csv('data/주말/2020_주말.csv', encoding='utf-8', sep=',')
df

           사용일자    호선명    지하철역  승차총승객수  하차총승객수  승하차총승객수 평일주말
0      20200104  우이신설선  북한산보국문    5117    4407     9524   주말
1      20200104    1호선     서울역   48376   46823    95199   주말
2      20200104    1호선      시청   22370   23449    45819   주말
3      20200104    1호선      종각   35345   33183    68528   주말
4      20200104    1호선    종로3가   34613   33921    68534   주말
...         ...    ...     ...     ...     ...      ...  ...
61637  20201227    6호선      대흥    1953    2023     3976   주말
61638  20201227    6호선     광흥창    1983    1999     3982   주말
61639  20201227    6호선      상수    2312    2726     5038   주말
61640  20201227    6호선      합정    4258    3832     8090   주말
61641  20201227    6호선      망원    4691    5016     9707   주말

[61642 rows x 7 columns]

In [6]:
# # 사용일자 슬라이싱 -> yyyymm 형태로
ym_list = []
for x in range(len(df.index)):
    ym_list.append(str(df.사용일자.values[x])[:6])
df['사용일자'] = ym_list

# # col수정: 사용일자 --> 사용월
df.rename(columns={'사용일자':'사용월'}, inplace=True)

KeyError: '사용일자'

In [4]:
# 주말 파일 새로 저장
df = df.to_csv('data/주말/2020_주말.csv', index=False, encoding='utf-8')
# 새파일 다시 열기
df1 = pd.read_csv('data/주말/2020_주말.csv', encoding='utf-8', sep=',')
df1

          사용월    호선명   지하철역  승차총승객수  하차총승객수  승하차총승객수 평일주말
0      202101    9호선     노들    1719    1527     3246   주말
1      202101  우이신설선  삼양사거리    1112    1102     2214   주말
2      202101  우이신설선     삼양     917    1019     1936   주말
3      202101  우이신설선     화계    1470    1315     2785   주말
4      202101  우이신설선    가오리    1653    1625     3278   주말
...       ...    ...    ...     ...     ...      ...  ...
62441  202112    8호선     암사    7207    7005    14212   주말
62442  202112    7호선   부평구청    2769    2615     5384   주말
62443  202112    7호선    굴포천    3769    3821     7590   주말
62444  202112    7호선  삼산체육관    2072    2018     4090   주말
62445  202112    7호선     상동    5930    5652    11582   주말

[62446 rows x 7 columns]

In [5]:
df['호선명'].nunique(), df.호선명.unique()

TypeError: 'NoneType' object is not subscriptable

In [ ]:
# 호선별 파일 분리 (1호선, 2호선,....) 반복문

In [ ]:
# isin 써보기
# # for names in df[df.행정구역구분명 == '시군'].names:
# if df.호선명.str.isin(lines1):    # split의 -1자리 값이 lines1중에 있다면

# replace 써보기
df3 = df.replace({'호선명': ['1호선','경부선','경원선','경인선','장항선']}, '1호선')
df3 = df.replace({'2호선':'2호선'},{'일산선':'3호선'})
df3 = df.replace({'호선명': ['일산선','3호선']}, '3호선')
df3 = df.replace({'호선명': ['4호선','과천선','안산선']}, '4호선')
df3 = df.replace({'호선명': ['수인선','분당선']}, '수인분당선')
df3.호선명.unique()

array(['9호선', '우이신설선', '안산선', '중앙선', '장항선', '일산선', '경인선', '수인분당선', '과천선',
       '공항철도 1호선', '경춘선', '경의선', '경원선', '경부선', '경강선', '9호선2~3단계', '8호선',
       '7호선', '6호선', '5호선', '4호선', '3호선', '2호선', '1호선'], dtype=object)

In [ ]:
df3.호선명.unique()

array(['9호선', '우이신설선', '안산선', '중앙선', '장항선', '일산선', '경인선', '수인분당선', '과천선',
       '공항철도 1호선', '경춘선', '경의선', '경원선', '경부선', '경강선', '9호선2~3단계', '8호선',
       '7호선', '6호선', '5호선', '4호선', '3호선', '2호선', '1호선'], dtype=object)